name: Validate ckans
on:
    push:
        branches:
            - master
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
jobs:
    Validate:
        runs-on: ubuntu-latest
        steps:
            - name: Get CKAN-meta repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Cache downloads
              uses: actions/cache@v2
              with:
                  path: /cache
                  key: downloads-${{ github.run_id }}
                  restore-keys: |
                      downloads-
            - name: Test modified ckans
              uses: HebaruSan/xKAN-meta_testing@github_action
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_BASE_REF: ${{ github.base_ref }}
              with:
                  source: commits
                  log level: debug
                  pull request body: ${{ github.event.pull_request.body }}
